CREATE TABLE SALES(
	SALES_ID INT NOT NULL AUTO_INCREMENT UNIQUE,
	ITEM_ID		INT(5),
	QTY 		INT(3),
	PRICE		DOUBLE(5),
	DATE_SOLD	DATE,
	SOLD_BY		STRING(40),
	PRIMARY KEY(SALES_ID),
	FOREIGN KEY(ITEM_ID) REFERENCES ITEMS(ITEM_ID)
);

CREATE TABLE ITEMS(
	ITEM_ID INT(5) NOT NULL,
	ITEM_NAME STRING(50),
	STOCK	INT(7),
	PRIMARY KEY(ITEM_ID)
);
